name: freal_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  get: ^4.6.5

  # Dependency injection
  get_it: ^7.2.0

  # Social login
  email_validator: ^2.1.17
  google_sign_in: ^6.2.1

  # Networking
  dio: ^5.4.0
  http: ^1.2.2
  dio_cache_interceptor: ^3.5.0

  # Utilities
  shared_preferences: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.18.1

  # Google
  google_maps_flutter: ^2.2.3
  google_fonts: 5.1.0

  # Firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_messaging: ^15.1.1
  firebase_crashlytics: ^4.1.1
  
  # UI 
  flutter_cache_manager: ^3.3.1
  cupertino_icons: ^1.0.6
  velocity_x: ^4.2.1
  otp_text_field: ^1.1.3
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  keyboard_dismisser: ^3.0.0
  logger: ^2.4.0
  localize_and_translate: ^5.1.2

dependency_overrides:
  flutter_svg: 1.1.6
  web3dart: ^2.3.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - .env

