// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rmOxPZPM6FX9wVGIZHWZnGffOHdP7BA',
    appId: '1:112943012458:web:73e57e854205235205c813',
    messagingSenderId: '112943012458',
    projectId: 'navel-flutter',
    authDomain: 'navel-flutter.firebaseapp.com',
    storageBucket: 'navel-flutter.appspot.com',
    measurementId: 'G-9ZP4XS99YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafmh22Uq_yuofEk9BBLGq55mBb_SFEZI',
    appId: '1:112943012458:android:0ed576caaecb344605c813',
    messagingSenderId: '112943012458',
    projectId: 'navel-flutter',
    storageBucket: 'navel-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzkpxHA3X0sSivh8f20imCui1OW6otuo',
    appId: '1:112943012458:ios:c0434f583190798a05c813',
    messagingSenderId: '112943012458',
    projectId: 'navel-flutter',
    storageBucket: 'navel-flutter.appspot.com',
    iosBundleId: 'com.example.frealFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzkpxHA3X0sSivh8f20imCui1OW6otuo',
    appId: '1:112943012458:ios:c0434f583190798a05c813',
    messagingSenderId: '112943012458',
    projectId: 'navel-flutter',
    storageBucket: 'navel-flutter.appspot.com',
    iosBundleId: 'com.example.frealFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8rmOxPZPM6FX9wVGIZHWZnGffOHdP7BA',
    appId: '1:112943012458:web:35d41d0870e3b34605c813',
    messagingSenderId: '112943012458',
    projectId: 'navel-flutter',
    authDomain: 'navel-flutter.firebaseapp.com',
    storageBucket: 'navel-flutter.appspot.com',
    measurementId: 'G-RPXC784NVX',
  );
}
